set(SIMULICORE_SYSTEM_LINUX 0)
set(SIMULICORE_SYSTEM_WIN32 0)
set(SIMULICORE_SYSTEM_MACOS 0)

set(SIMULICORE_ARCH_X86_64 0)
set(SIMULICORE_ARCH_ARM64 0)

if((${CMAKE_SYSTEM_NAME} STREQUAL "Linux") AND (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64"))

	set(SIMULICORE_SYSTEM_LINUX 1)
	set(SIMULICORE_ARCH_X86_64 1)

elseif((${CMAKE_SYSTEM_NAME} STREQUAL "Windows") AND ((${CMAKE_SYSTEM_PROCESSOR} STREQUAL "AMD64") OR (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")))

	set(SIMULICORE_SYSTEM_WIN32 1)
	set(SIMULICORE_ARCH_X86_64 1)

elseif((${CMAKE_SYSTEM_NAME} STREQUAL "Darwin") AND (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "arm64"))

	set(SIMULICORE_SYSTEM_MACOS 1)
	set(SIMULICORE_ARCH_ARM64 1)

else()

	message(FATAL_ERROR "Unsupported System: ${CMAKE_SYSTEM_NAME} (${CMAKE_SYSTEM_PROCESSOR})")

endif()
